# set base image (host OS)
FROM ghcr.io/astral-sh/uv:python3.12-bookworm

# set the working directory in the container
WORKDIR /code

ENV DGLBACKEND=pytorch

# Copy required files to the workdir.
COPY src /code/src
COPY pyproject.toml /code/pyproject.toml
COPY tests /code/tests
COPY run_tests.sh /code/run_tests.sh

# install dependencies
RUN uv sync
RUN uv pip install -e '.[ci]'

# command to run on container start
CMD [ "uv", "run", "./run_tests.sh" ]
