name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Virtual env
        run: uv venv
      - name: Install latest DGL for Linux
        run: uv pip install dgl==2.4.0 -f https://data.dgl.ai/wheels/torch-2.4/repo.html
      - name: Install dependencies
        run: |
          uv pip install -e .
          uv pip install ruff mypy

      - name: ruff
        run: |
          uv run ruff --version
          uv run ruff check src
          uv run ruff format src --check
      - name: mypy
        run: |
          uv run mypy --version
          rm -rf .mypy_cache
          uv run mypy -p matgl
