name: Linting

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install --quiet -r requirements-ci.txt
      - name: ruff
        run: |
          ruff --version
          ruff check matgl
      - name: black
        run: |
          black --version
          black --check --diff --color matgl
      - name: mypy
        run: |
          mypy --version
          rm -rf .mypy_cache
          mypy matgl
